# Generated by Django 4.2.17 on 2024-12-25 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0001_initial'),
    ]

    operations = [
    ]
