# Generated by Django 4.2.17 on 2024-12-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0004_alter_cow_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='tag_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cow',
            unique_together={('farm', 'tag_number')},
        ),
    ]
