# Generated by Django 4.2.17 on 2024-12-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0005_alter_cow_tag_number_alter_cow_unique_together'),
    ]

    operations = [
    ]
