# Generated by Django 4.2.17 on 2024-12-29 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0006_auto_20241226_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'permissions': [('manage_farm', 'Can manage farm settings'), ('manage_workers', 'Can manage farm workers'), ('view_reports', 'Can view farm reports')]},
        ),
        migrations.AlterField(
            model_name='milkproduction',
            name='evening_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='milkproduction',
            name='morning_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
