# Generated by Django 4.2.17 on 2024-12-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0006_auto_20241226_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'permissions': [('manage_farm', 'Can manage farm settings'), ('manage_workers', 'Can manage farm workers'), ('view_reports', 'Can view farm reports')]},
        ),
    ]
