# Generated by Django 4.2.17 on 2024-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0007_alter_farm_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='acquired_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='cause_of_death',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='maternal_ancestry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='paternal_ancestry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cow',
            name='sold_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
